development:
  port: 3080
  db: mongodb://localhost/mywebclass_dev
  app:
    name: MyWebClass Development Version
    url: http://node.mywebclass.org
  google:
    realm: http://node.mywebclass.org
    callbackURL: http://node.mywebclass.org/auth/google/return
  smtp:
    service: Gmail
    user: USER@DOMAIN
    pass: PASSWORD
  confirmationLinkExpire: 1

test:
  port: 3080
  db: mongodb://localhost/mywebclass_test
  app:
    name: MyWebClass Testing Version
    url: http://node.mywebclass.org
  google:
    realm: http://node.mywebclass.org
    callbackURL: http://node.mywebclass.org/auth/google/return
  smtp:
    service: Gmail
    user: USER@DOMAIN
    pass: PASSWORD
  confirmationLinkExpire: 1

production:
  port: 80
  db: mongodb://localhost/mywebclass
  app:
    name: MyWebClass
    url: http://node.mywebclass.org
  google:
    realm: http://node.mywebclass.org
    callbackURL: http://node.mywebclass.org/auth/google/return
  smtp:
    service: Gmail
    user: USER@DOMAIN
    pass: PASSWORD
  confirmationLinkExpire: 72
